wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705417408.894668
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      3:
      - 7
      - 23
      4: 3.11.7
      5: 0.16.2
      6: 4.32.1
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
in_features:
  desc: null
  value:
  - 28
  - 28
out_features:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.005
